### ISSUE TITLE
22.09 release task list

### ISSUE THREAD

**Issue by falkTX** [DISTRHO/Cardinal#377]
a meta-ticket to track down things to do for 22.09 release, in case anyone wants to follow along and possibly help too.

- [x] fix gui not displaying on some windows hosts #373 
- [x] add readme (and docs, screenshots) to zip artifact downloads #363 
- [x] AU format out of tune #315 related to https://github.com/juce-framework/JUCE/pull/1097
- [x] VST2 crashes when removing 2nd instance #273 related to https://github.com/trummerschlunk/master_me/issues/78
- [x] samples are either not saved or not restored #236 
- [x] check for new modules needing dark theme patching and adjust for them
- [x] fix fundamental swapped control
- [x] fix fundamental light mode
- [x] make list of modules needing light mode patching
- [x] complete light mode #378 
- [x] get clap midi working in bitwig

skipped:
- update fundamental to add new panels

**Comment by falkTX** [comment]
@offthesky I will skip fundamental update this time around again. the setup for the light panels took waaaay too long and I need to do releases on other projects, so non-critical things are pushed to another release.

**Comment by offthesky** [comment]
> @offthesky I will skip fundamental update this time around again. the setup for the light panels took waaaay too long and I need to do releases on other projects, so non-critical things are pushed to another release.

thats no problem ty for the heads up! i think we can achieve mostly the same logic type results with certain bog audio modules anyway.
