### ISSUE TITLE
Light mode module list TODO

### ISSUE THREAD

**Issue by falkTX** [DISTRHO/Cardinal#378]
A ticket to track progress of light mode panels

- [x] 8mode softSN needs light patching
- [x] animated circuits needs custom handling
- [x] autinn needs custom handling
- [x] Cardinal/Core Sassy scope buttons have black text on black background
- [x] Cardinal/Core Text editor looks bad in light mode (GL2 only??)
- [x] Extratone TODO
- [x] Fehler fabrick TODO
- [x] Fundamental needs custom handling
- [x] Glue the Giant needs custom handling
- [x] GoodShepperd TODO
- [x] H4N4 TODO
- [x] MSM needs custom handling
- [x] Mockba TODO
- [x] Mog TODO
- [x] Prism TODO
- [x] repelzen TODO
- [x] valleyaudio needs custom handling

should not have screw changed to black automatically:
- [x] Arable instruments Joni
- [x] axioma
- [x] Parable instruments Neil
- [x] rackwindows

undecided:
- amalgated harmonics
- AS (would need custom permission)
- JW blank cat??
- Orbits (would need custom permission)
- ZZC (would need custom permission)

wont do:
- Bacon modules need custom handling

**Comment by falkTX** [comment]
undecided means "too tired of custom patching for light theme which I wont ever use anyway, this seems good enough"
module devs should make their own light theme eventually, hopefully.
let's move on
